//! `host-api.lock` emit, parse, and diff.
//!
//! The lockfile is a plain-text contract document, not machine-read
//! config. Sections are prefixed with `##` so humans can grep; values
//! are one-per-line. Everything is sorted lexicographically so the
//! output is byte-stable across rebuilds and platforms.

use std::collections::BTreeSet;
use std::path::PathBuf;

use super::surface::SurfaceDescription;

/// Header comment block at the top of every emitted `host-api.lock`.
/// Deliberately does NOT contain a timestamp — determinism beats
/// provenance, and `git blame` carries the "when" signal already.
pub const LOCKFILE_HEADER: &str = "\
# permitlayer host-api.lock
# Generated by `cargo xtask validate-plugin-api`.
# Do NOT edit by hand. To regenerate:
#   cargo xtask validate-plugin-api --update
#
# This file is part of the NFR41 semver contract.
# Any change that is not covered by a major-version bump of HOST_API_VERSION
# (and a 6-month deprecation entry for removed surface) is a breaking change
# that CI will reject.
";

/// Path to the committed lockfile, honoring the `HOST_API_LOCK_PATH`
/// test seam in debug builds.
pub fn lockfile_path() -> PathBuf {
    #[cfg(debug_assertions)]
    {
        if let Ok(p) = std::env::var("HOST_API_LOCK_PATH")
            && !p.is_empty()
        {
            return PathBuf::from(p);
        }
    }
    workspace_root().join("host-api.lock")
}

/// `<workspace>` — `<xtask>/../`. The xtask's `CARGO_MANIFEST_DIR`
/// is `<workspace>/xtask`.
pub fn workspace_root() -> PathBuf {
    let xtask_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    xtask_dir.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| xtask_dir.clone())
}

/// Render a [`SurfaceDescription`] as the on-disk text form.
///
/// Guarantees:
/// - LF-only line endings (no CRLF on Windows).
/// - Lexicographic ordering within each section.
/// - Single trailing LF (POSIX-friendly).
/// - Byte-identical output across repeated runs.
pub fn emit(desc: &SurfaceDescription) -> String {
    let mut out = String::new();
    out.push_str(LOCKFILE_HEADER);
    out.push('\n');

    emit_section(
        &mut out,
        "version",
        std::iter::once(format!("HOST_API_VERSION = {}", desc.version)),
    );
    emit_section(&mut out, "js_surface", desc.js_surface.iter().cloned());
    emit_section_with_suffix(
        &mut out,
        "error_codes",
        desc.error_codes.iter().cloned(),
        Some(
            "# Plus: HostApiErrorCode::Other(String) for plugin-custom codes (not listed individually).",
        ),
    );
    emit_section(&mut out, "host_services_trait", desc.host_services_methods.iter().cloned());
    emit_section(&mut out, "dto_shapes", desc.dto_shapes.iter().cloned());

    // `emit_section` appends a blank separator after each section;
    // strip the final one so the file ends with exactly one trailing
    // LF (AC #3).
    while out.ends_with("\n\n") {
        out.pop();
    }

    out
}

fn emit_section<I: IntoIterator<Item = String>>(out: &mut String, name: &str, lines: I) {
    out.push_str(&format!("## {name}\n"));
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out.push('\n');
}

fn emit_section_with_suffix<I: IntoIterator<Item = String>>(
    out: &mut String,
    name: &str,
    lines: I,
    suffix: Option<&str>,
) {
    out.push_str(&format!("## {name}\n"));
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    if let Some(s) = suffix {
        out.push_str(s);
        out.push('\n');
    }
    out.push('\n');
}

/// Parse an on-disk lockfile back into a [`SurfaceDescription`].
///
/// Accepts the exact shape [`emit`] produces; lenient about trailing
/// whitespace + missing trailing newline. Does NOT enforce sort order
/// on read (we re-sort via `BTreeSet` anyway), but DOES require every
/// section to be present.
pub fn parse(content: &str) -> anyhow::Result<SurfaceDescription> {
    use anyhow::{Context, anyhow, bail};

    let mut version: Option<String> = None;
    let mut js_surface: BTreeSet<String> = BTreeSet::new();
    let mut error_codes: BTreeSet<String> = BTreeSet::new();
    let mut host_services_methods: BTreeSet<String> = BTreeSet::new();
    let mut dto_shapes: BTreeSet<String> = BTreeSet::new();

    let mut current: Option<&'static str> = None;
    for (idx, raw) in content.lines().enumerate() {
        let line = raw.trim_end();
        // Skip empty lines and single-hash comment lines.
        // Section headers start with `## ` — they are NOT skipped here.
        if line.is_empty() || (line.starts_with('#') && !line.starts_with("## ")) {
            continue;
        }
        if let Some(rest) = line.strip_prefix("## ") {
            current = Some(match rest {
                "version" => "version",
                "js_surface" => "js_surface",
                "error_codes" => "error_codes",
                "host_services_trait" => "host_services_trait",
                "dto_shapes" => "dto_shapes",
                other => bail!(
                    "unknown section header `## {other}` on line {}; valid sections: version, js_surface, error_codes, host_services_trait, dto_shapes",
                    idx + 1
                ),
            });
            continue;
        }
        match current {
            Some("version") => {
                let rest = line
                    .strip_prefix("HOST_API_VERSION = ")
                    .context("version section line must start with `HOST_API_VERSION = `")?;
                version = Some(rest.to_owned());
            }
            Some("js_surface") => {
                js_surface.insert(line.to_owned());
            }
            Some("error_codes") => {
                error_codes.insert(line.to_owned());
            }
            Some("host_services_trait") => {
                host_services_methods.insert(line.to_owned());
            }
            Some("dto_shapes") => {
                dto_shapes.insert(line.to_owned());
            }
            Some(other) => {
                bail!("internal: unexpected current section `{other}` on line {}", idx + 1);
            }
            None => {
                bail!("line {} appears before any `## <section>` header", idx + 1);
            }
        }
    }

    Ok(SurfaceDescription {
        version: version.ok_or_else(|| anyhow!("missing `## version` section"))?,
        js_surface,
        error_codes,
        host_services_methods,
        dto_shapes,
    })
}

/// Diff result between a committed lockfile and the live surface.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SurfaceDiff {
    /// Version change, if any. Populated iff `committed.version !=
    /// live.version`.
    pub version_change: Option<(String, String)>,
    /// Entries present in `committed` but missing from `live`.
    /// Removals from the surface.
    pub removed_js_surface: Vec<String>,
    pub added_js_surface: Vec<String>,
    pub removed_error_codes: Vec<String>,
    pub added_error_codes: Vec<String>,
    pub removed_host_services_methods: Vec<String>,
    pub added_host_services_methods: Vec<String>,
    pub removed_dto_shapes: Vec<String>,
    pub added_dto_shapes: Vec<String>,
}

impl SurfaceDiff {
    /// A diff is empty iff the live surface matches the committed
    /// lockfile byte-for-byte (modulo the header).
    pub fn is_empty(&self) -> bool {
        self.version_change.is_none()
            && self.removed_js_surface.is_empty()
            && self.added_js_surface.is_empty()
            && self.removed_error_codes.is_empty()
            && self.added_error_codes.is_empty()
            && self.removed_host_services_methods.is_empty()
            && self.added_host_services_methods.is_empty()
            && self.removed_dto_shapes.is_empty()
            && self.added_dto_shapes.is_empty()
    }

    /// Does the diff contain a removal or signature change?
    /// (Signature changes surface as paired removed+added entries.)
    pub fn has_removals(&self) -> bool {
        !self.removed_js_surface.is_empty()
            || !self.removed_error_codes.is_empty()
            || !self.removed_host_services_methods.is_empty()
            || !self.removed_dto_shapes.is_empty()
    }

    /// Does the diff contain only additions (no removals, no
    /// signature changes, no version change)?
    pub fn is_purely_additive(&self) -> bool {
        self.version_change.is_none() && !self.has_removals()
    }

    /// Render the diff as a human-readable block for stdout/stderr.
    pub fn render(&self) -> String {
        let mut out = String::new();
        if let Some((old, new)) = &self.version_change {
            out.push_str(&format!("  - version: {old} → {new}\n"));
        }
        render_section(&mut out, "js_surface", &self.removed_js_surface, &self.added_js_surface);
        render_section(&mut out, "error_codes", &self.removed_error_codes, &self.added_error_codes);
        render_section(
            &mut out,
            "host_services_trait",
            &self.removed_host_services_methods,
            &self.added_host_services_methods,
        );
        render_section(&mut out, "dto_shapes", &self.removed_dto_shapes, &self.added_dto_shapes);
        out
    }
}

fn render_section(out: &mut String, name: &str, removed: &[String], added: &[String]) {
    if removed.is_empty() && added.is_empty() {
        return;
    }
    out.push_str(&format!("  ## {name}\n"));
    for line in removed {
        out.push_str(&format!("  - {line}\n"));
    }
    for line in added {
        out.push_str(&format!("  + {line}\n"));
    }
}

/// Compute the diff between a committed surface and the live surface.
pub fn diff(committed: &SurfaceDescription, live: &SurfaceDescription) -> SurfaceDiff {
    let mut d = SurfaceDiff::default();
    if committed.version != live.version {
        d.version_change = Some((committed.version.clone(), live.version.clone()));
    }
    (d.removed_js_surface, d.added_js_surface) = set_diff(&committed.js_surface, &live.js_surface);
    (d.removed_error_codes, d.added_error_codes) =
        set_diff(&committed.error_codes, &live.error_codes);
    (d.removed_host_services_methods, d.added_host_services_methods) =
        set_diff(&committed.host_services_methods, &live.host_services_methods);
    (d.removed_dto_shapes, d.added_dto_shapes) = set_diff(&committed.dto_shapes, &live.dto_shapes);
    d
}

fn set_diff(old: &BTreeSet<String>, new: &BTreeSet<String>) -> (Vec<String>, Vec<String>) {
    let removed = old.difference(new).cloned().collect();
    let added = new.difference(old).cloned().collect();
    (removed, added)
}
