//! Proxy request type: the validated, middleware-enriched payload that
//! reaches `ProxyService::handle`.

use axum::body::Bytes;
use axum::http::{HeaderMap, Method};

/// A validated proxy request ready for upstream dispatch.
///
/// Constructed from an incoming axum `Request` after the middleware chain
/// has extracted authentication, agent identity, and tracing context.
pub struct ProxyRequest {
    /// Upstream service name (e.g., "gmail").
    pub service: String,
    /// OAuth scope the agent is requesting (from `X-Agentsso-Scope` header,
    /// or `"*"` if absent).
    pub scope: String,
    /// Resource path after the service segment (e.g., "users/me/messages/123").
    pub resource: String,
    /// HTTP method for the upstream call.
    pub method: Method,
    /// URL path for the upstream API (same as resource).
    pub path: String,
    /// HTTP headers to forward (stripped of auth headers by middleware).
    pub headers: HeaderMap,
    /// Request body bytes.
    pub body: Bytes,
    /// Agent identity, resolved from bearer token by `AgentIdentityLayer`.
    pub agent_id: String,
    /// ULID request ID, generated by `RequestTraceLayer`.
    pub request_id: String,
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn construct_proxy_request() {
        let req = ProxyRequest {
            service: "gmail".to_owned(),
            scope: "mail.readonly".to_owned(),
            resource: "users/me/messages".to_owned(),
            method: Method::GET,
            path: "users/me/messages".to_owned(),
            headers: HeaderMap::new(),
            body: Bytes::new(),
            agent_id: "agent-1".to_owned(),
            request_id: "01TESTULID".to_owned(),
        };
        assert_eq!(req.service, "gmail");
        assert_eq!(req.scope, "mail.readonly");
        assert_eq!(req.resource, "users/me/messages");
        assert_eq!(req.method, Method::GET);
        assert_eq!(req.agent_id, "agent-1");
        assert_eq!(req.request_id, "01TESTULID");
    }
}
