// @generated by build.rs from tokens.json — DO NOT EDIT

/// Semantic color tokens for a single theme.
#[derive(Debug, Clone, Copy)]
pub struct ThemeTokens {
    pub accent: &'static str,
    pub accent_soft: &'static str,
    pub accent_strong: &'static str,
    pub bg_0: &'static str,
    pub bg_1: &'static str,
    pub bg_2: &'static str,
    pub bg_3: &'static str,
    pub border: &'static str,
    pub border_strong: &'static str,
    pub danger: &'static str,
    pub info: &'static str,
    pub muted: &'static str,
    pub scrub: &'static str,
    pub success: &'static str,
    pub text_0: &'static str,
    pub text_1: &'static str,
    pub text_2: &'static str,
    pub text_3: &'static str,
    pub warn: &'static str,
}

pub const CARAPACE: ThemeTokens = ThemeTokens {
    accent: "#2DD4BF",
    accent_soft: "#0F3D3A",
    accent_strong: "#14B8A6",
    bg_0: "#0E1014",
    bg_1: "#14171D",
    bg_2: "#1C2028",
    bg_3: "#252A34",
    border: "#2F3542",
    border_strong: "#3F4757",
    danger: "#EF6F6C",
    info: "#7DD3FC",
    muted: "#6B7280",
    scrub: "#F5B454",
    success: "#4ADE80",
    text_0: "#F4F5F7",
    text_1: "#C6CAD3",
    text_2: "#8A91A0",
    text_3: "#5A6170",
    warn: "#F5B454",
};

pub const MOLT: ThemeTokens = ThemeTokens {
    accent: "#0D9488",
    accent_soft: "#CCFBF1",
    accent_strong: "#0F766E",
    bg_0: "#FBFAF7",
    bg_1: "#F0EDE6",
    bg_2: "#E4E0D8",
    bg_3: "#D8D3C9",
    border: "#C4BEB4",
    border_strong: "#A8A196",
    danger: "#DC2626",
    info: "#0284C7",
    muted: "#6B7280",
    scrub: "#D97706",
    success: "#16A34A",
    text_0: "#1C2028",
    text_1: "#3A3F4A",
    text_2: "#5A6170",
    text_3: "#8A91A0",
    warn: "#D97706",
};

pub const TIDEPOOL: ThemeTokens = ThemeTokens {
    accent: "#94E2D5",
    accent_soft: "#1E3A3A",
    accent_strong: "#74D0C3",
    bg_0: "#1E1E2E",
    bg_1: "#24243A",
    bg_2: "#2A2A46",
    bg_3: "#313152",
    border: "#3B3B5C",
    border_strong: "#4E4E72",
    danger: "#F38BA8",
    info: "#89B4FA",
    muted: "#6C7086",
    scrub: "#F9E2AF",
    success: "#A6E3A1",
    text_0: "#CDD6F4",
    text_1: "#BAC2DE",
    text_2: "#A6ADC8",
    text_3: "#6C7086",
    warn: "#F9E2AF",
};

pub const MONO_FONT: &str = "JetBrains Mono, Fira Code, monospace";

pub const SPACE: [u16; 8] = [4, 8, 12, 16, 20, 24, 28, 32];

pub const SPACE_1: u16 = 4;
pub const SPACE_2: u16 = 8;
pub const SPACE_3: u16 = 12;
pub const SPACE_4: u16 = 16;
pub const SPACE_5: u16 = 20;
pub const SPACE_6: u16 = 24;
pub const SPACE_7: u16 = 28;
pub const SPACE_8: u16 = 32;

pub const RADIUS_FULL: u16 = 9999;
pub const RADIUS_LG: u16 = 12;
pub const RADIUS_MD: u16 = 8;
pub const RADIUS_SM: u16 = 4;
pub const RADIUS_XL: u16 = 16;

/// Glass-morphism elevation level.
#[derive(Debug, Clone, Copy)]
pub struct GlassLevel {
    pub bg_alpha: f32,
    pub blur: u16,
    pub border_alpha: f32,
}

pub const GLASS_1: GlassLevel = GlassLevel { bg_alpha: 0.72_f32, blur: 12, border_alpha: 0.6_f32 };
pub const GLASS_2: GlassLevel = GlassLevel { bg_alpha: 0.8_f32, blur: 20, border_alpha: 0.6_f32 };
pub const GLASS_3: GlassLevel = GlassLevel { bg_alpha: 0.85_f32, blur: 28, border_alpha: 0.8_f32 };
