//! Build script: reads `tokens.json` from the workspace root and generates
//! `src/design/generated_tokens.rs` with `const` token definitions.

// Build scripts are not production runtime code — expect/panic are the
// standard error-reporting mechanism (a panic fails the build).
#![allow(clippy::expect_used, clippy::panic)]

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let tokens_path = Path::new(&manifest_dir).join("../../tokens.json");
    println!("cargo:rerun-if-changed={}", tokens_path.display());

    let contents = std::fs::read_to_string(tokens_path)
        .expect("failed to read tokens.json — ensure it exists at the workspace root");

    let root: serde_json::Value =
        serde_json::from_str(&contents).expect("tokens.json is not valid JSON");

    let mut out = String::with_capacity(8192);
    writeln!(out, "// @generated by build.rs from tokens.json — DO NOT EDIT").ok();
    writeln!(out).ok();

    // ── Color tokens per theme ─────────────────────────────────────────

    let colors = root["color"].as_object().expect("tokens.json: missing `color` object");

    // Collect token names from the first theme to keep order consistent.
    let first_theme_tokens: Vec<String> = {
        let first = colors.values().next().expect("no themes in color object");
        first.as_object().expect("theme is not an object").keys().cloned().collect()
    };

    writeln!(out, "/// Semantic color tokens for a single theme.").ok();
    writeln!(out, "#[derive(Debug, Clone, Copy)]").ok();
    writeln!(out, "pub struct ThemeTokens {{").ok();
    for token in &first_theme_tokens {
        let field = token.replace('-', "_");
        writeln!(out, "    pub {field}: &'static str,").ok();
    }
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    // Generate a const for each theme.
    for (theme_name, theme_value) in colors {
        let tokens: BTreeMap<String, String> = theme_value
            .as_object()
            .expect("theme is not an object")
            .iter()
            .map(|(k, v)| {
                (
                    k.clone(),
                    v.as_str()
                        .unwrap_or_else(|| panic!("color token {k} is not a string"))
                        .to_owned(),
                )
            })
            .collect();

        let const_name = theme_name.to_uppercase();
        writeln!(out, "pub const {const_name}: ThemeTokens = ThemeTokens {{").ok();
        for token in &first_theme_tokens {
            let field = token.replace('-', "_");
            let value = tokens
                .get(token)
                .unwrap_or_else(|| panic!("theme {theme_name} is missing token {token}"));
            writeln!(out, "    {field}: \"{value}\",").ok();
        }
        writeln!(out, "}};").ok();
        writeln!(out).ok();
    }

    // ── Typography ─────────────────────────────────────────────────────

    if let Some(type_obj) = root["type"].as_object()
        && let Some(mono) = type_obj.get("mono").and_then(|v| v.as_str())
    {
        writeln!(out, "pub const MONO_FONT: &str = \"{mono}\";").ok();
        writeln!(out).ok();
    }

    // ── Spacing grid ───────────────────────────────────────────────────

    if let Some(space_arr) = root["space"].as_array() {
        let values: Vec<String> = space_arr
            .iter()
            .map(|v| {
                v.as_u64().unwrap_or_else(|| panic!("space value is not an integer")).to_string()
            })
            .collect();

        writeln!(out, "pub const SPACE: [u16; {}] = [{}];", values.len(), values.join(", ")).ok();
        writeln!(out).ok();

        // Named constants for convenience.
        for (i, val) in values.iter().enumerate() {
            writeln!(out, "pub const SPACE_{}: u16 = {val};", i + 1).ok();
        }
        writeln!(out).ok();
    }

    // ── Radius scale ───────────────────────────────────────────────────

    if let Some(radius_obj) = root["radius"].as_object() {
        for (name, value) in radius_obj {
            let const_name = format!("RADIUS_{}", name.to_uppercase());
            let val =
                value.as_u64().unwrap_or_else(|| panic!("radius value {name} is not an integer"));
            writeln!(out, "pub const {const_name}: u16 = {val};").ok();
        }
        writeln!(out).ok();
    }

    // ── Elevation / glass levels ───────────────────────────────────────

    if let Some(elevation_obj) = root["elevation"].as_object() {
        writeln!(out, "/// Glass-morphism elevation level.").ok();
        writeln!(out, "#[derive(Debug, Clone, Copy)]").ok();
        writeln!(out, "pub struct GlassLevel {{").ok();
        writeln!(out, "    pub bg_alpha: f32,").ok();
        writeln!(out, "    pub blur: u16,").ok();
        writeln!(out, "    pub border_alpha: f32,").ok();
        writeln!(out, "}}").ok();
        writeln!(out).ok();

        for (name, value) in elevation_obj {
            let const_name = name.to_uppercase().replace('-', "_");
            let bg_alpha = value["bg-alpha"]
                .as_f64()
                .unwrap_or_else(|| panic!("elevation {name} missing bg-alpha"));
            let blur =
                value["blur"].as_u64().unwrap_or_else(|| panic!("elevation {name} missing blur"));
            let border_alpha = value["border-alpha"]
                .as_f64()
                .unwrap_or_else(|| panic!("elevation {name} missing border-alpha"));

            writeln!(
                out,
                "pub const {const_name}: GlassLevel = GlassLevel {{ bg_alpha: {bg_alpha}_f32, blur: {blur}, border_alpha: {border_alpha}_f32 }};",
            )
            .ok();
        }
        writeln!(out).ok();
    }

    // Write the generated file. Trim trailing whitespace so rustfmt is happy.
    let out = out.trim_end().to_string() + "\n";
    let out_path = Path::new("src/design/generated_tokens.rs");
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(out_path, out).expect("failed to write generated_tokens.rs");
}
